name: Build and Deploy Javadocs

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Javadocs

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Install dependencies and generate Javadocs
        run: mvn clean install -B -q -Dgpg.skip=true javadoc:javadoc javadoc:jar

      # Upload the Javadocs as an artifact to be deployed
      - name: Upload Javadocs Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: target/reports/apidocs

  deploy:
    name: Deploy Javadocs to GitHub Pages

    runs-on: ubuntu-latest
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
